# Manual acronym overrides. These entries take precedence over corpus-derived mappings.
# Use either a single string expansion or a list of possible expansions.
#
# Examples:
# EPS: "Electrical Power Subsystem"
# T&C:
#   - "Telemetry and Command"
#   - "Tracking and Control"

NASA: "National Aeronautics and Space Administration"
JPL: "Jet Propulsion Laboratory"
GSFC: "Goddard Space Flight Center"
MSFC: "Marshall Space Flight Center"
ESA: "European Space Agency"
JAXA: "Japan Aerospace Exploration Agency"
ISRO: "Indian Space Research Organisation"
CNES: "Centre National d'Études Spatiales"
DLR: "Deutsches Zentrum für Luft- und Raumfahrt"
KARI: "Korea Aerospace Research Institute"